import { BlogCardProps } from '@/components/cards/BlogCard';

// Mock data for blog posts
export const blogPosts: BlogCardProps[] = [
  {
    id: '1',
    slug: 'freelance-success-tips',
    title: '10 Essential Tips for Freelance Success in 2023',
    excerpt: 'Discover the key strategies that successful freelancers are using to find high-paying clients and build sustainable businesses.',
    author: {
      name: 'Jessica Miller',
      avatar: '/user-avatar.svg',
    },
    category: 'Tips & Tricks',
    publishDate: 'June 15, 2023',
    readTime: '5 min read',
    imageUrl: '/blog-post.svg',
  },
  {
    id: '2',
    slug: 'youtube-algorithm-changes',
    title: 'Understanding YouTube\'s Latest Algorithm Changes',
    excerpt: 'A detailed breakdown of the recent YouTube algorithm updates and how content creators can adapt their strategies accordingly.',
    author: {
       name: 'David Wong',
       avatar: '/user-avatar.svg',
     },
    category: 'Content Creation',
    publishDate: 'June 10, 2023',
    readTime: '8 min read',
    imageUrl: '/blog-post.svg',
  },
  {
    id: '3',
    slug: 'passive-income-strategies',
    title: '7 Passive Income Strategies That Actually Work',
    excerpt: 'Explore proven passive income strategies that can help you build wealth and achieve financial freedom over time.',
    author: {
      name: 'Michael Chen',
      avatar: '/user-avatar.svg',
    },
    category: 'Investing',
    publishDate: 'June 5, 2023',
    readTime: '10 min read',
    imageUrl: '/blog-post.svg',
  },
  {
    id: '4',
    slug: 'seo-for-beginners',
    title: 'SEO for Beginners: A Step-by-Step Guide',
    excerpt: 'Learn the fundamentals of search engine optimization and how to improve your website\'s visibility in search results.',
    author: {
      name: 'Emily Rodriguez',
      avatar: '/user-avatar.svg',
    },
    category: 'Marketing',
    publishDate: 'May 28, 2023',
    readTime: '12 min read',
    imageUrl: '/blog-post.svg',
  },
  {
    id: '5',
    slug: 'stock-market-basics',
    title: 'Stock Market Basics: What Every Beginner Should Know',
    excerpt: 'A comprehensive introduction to the stock market, including key terminology, how to start investing, and common pitfalls to avoid.',
    author: {
      name: 'Alex Rivera',
      avatar: '/user-avatar.svg',
    },
    category: 'Trading',
    publishDate: 'May 20, 2023',
    readTime: '15 min read',
    imageUrl: '/placeholder-blog.svg',
  },
  {
    id: '6',
    slug: 'client-communication',
    title: 'Mastering Client Communication for Freelancers',
    excerpt: 'Effective communication strategies that will help you build stronger client relationships and secure more repeat business.',
    author: {
      name: 'Sarah Johnson',
      avatar: '/user-avatar.svg',
    },
    category: 'Freelancing',
    publishDate: 'May 15, 2023',
    readTime: '7 min read',
    imageUrl: '/placeholder-blog.svg',
  },
  {
    id: '7',
    slug: 'time-management-hacks',
    title: '5 Time Management Hacks That Will Double Your Productivity',
    excerpt: 'Master these simple but powerful time management techniques to dramatically increase your productivity and reduce stress.',
    author: {
      name: 'Jessica Miller',
      avatar: '/user-avatar.svg',
    },
    category: 'Tips & Tricks',
    publishDate: 'May 10, 2023',
    readTime: '6 min read',
    imageUrl: '/placeholder-blog.svg',
  },
  {
    id: '8',
    slug: 'content-creation-tools',
    title: 'The Best Content Creation Tools for 2023',
    excerpt: 'A curated list of the most effective tools and software that will help you create better content more efficiently.',
    author: {
      name: 'David Wong',
      avatar: '/user-avatar.svg',
    },
    category: 'Content Creation',
    publishDate: 'May 5, 2023',
    readTime: '9 min read',
    imageUrl: '/placeholder-blog.svg',
  },
  {
    id: '9',
    slug: 'real-estate-investing',
    title: 'Real Estate Investing for Beginners',
    excerpt: 'A comprehensive guide to getting started with real estate investing, from property selection to financing options.',
    author: {
      name: 'Michael Chen',
      avatar: '/user-avatar.svg',
    },
    category: 'Investing',
    publishDate: 'April 30, 2023',
    readTime: '14 min read',
    imageUrl: '/placeholder-blog.svg',
  }
];